const astroObjects = [
    {   
        "name":"Неизвестно",
        "type":"",
        "astroX":"",
        "astroY":"",
        "astroZ":"",
        "directions":[]
    },
    {
        "name":"Персефона",
        "type":"planet",
        "astroX":1098,
        "astroY":202,
        "astroZ":572,
        "directions":[
            {
                "name":"Крамп",
                "type":"planet",
                "astroX":1335,
                "astroY":83,
                "astroZ":620,
                "fuel":5522
            },
            {
                "name":"РКЗП-128о",
                "type":"gasstation",
                "astroX":1227,
                "astroY":256,
                "astroZ":576,
                "fuel":321
            },
            {
                "name":"РКЗП-546",
                "type":"gasstation",
                "astroX":1129,
                "astroY":390,
                "astroZ":708,
                "fuel":309
            },
            {
                "name":"Сакулак",
                "type":"planet",
                "astroX":933,
                "astroY":301,
                "astroZ":620,
                "fuel":300
            }
        ]
    },
    {
        "name":"Крамп",
        "type":"planet",
        "astroX":1335,
        "astroY":83,
        "astroZ":620,
        "directions":[
            {
                "name":"Персефона",
                "type":"planet",
                "astroX":1098,
                "astroY":202,
                "astroZ":572,
                "fuel":5522
            }
        ]
    },
    {
        "name":"РКЗП-128о",
        "type":"gasstation",
        "astroX":1227,
        "astroY":256,
        "astroZ":576,
        "directions":[
            {
                "name":"Персефона",
                "type":"planet",
                "astroX":1098,
                "astroY":202,
                "astroZ":572,
                "fuel":321
            }
        ]
    },
    {
        "name":"РКЗП-546",
        "type":"gasstation",
        "astroX":1129,
        "astroY":390,
        "astroZ":708,
        "directions":[
            {
                "name":"Персефона",
                "type":"planet",
                "astroX":1098,
                "astroY":202,
                "astroZ":572,
                "fuel":309
            }
        ]
    },
    {
        "name":"Сакулак",
        "type":"planet",
        "astroX":933,
        "astroY":301,
        "astroZ":620,
        "directions":[
            {
                "name":"Персефона",
                "type":"planet",
                "astroX":1098,
                "astroY":202,
                "astroZ":572,
                "fuel":300
            },
            {
                "name":"Флостон",
                "type":"planet",
                "astroX":999,
                "astroY":475,
                "astroZ":620,
                "fuel":3854
            },
            {
                "name":"РКЗП-4568",
                "type":"gasstation",
                "astroX":949,
                "astroY":83,
                "astroZ":592,
                "fuel":347
            },
            {
                "name":"Вишну",
                "type":"planet",
                "astroX":711,
                "astroY":163,
                "astroZ":620,
                "fuel":5781
            },
            {
                "name":"РКЗП-1649",
                "type":"gasstation",
                "astroX":709,
                "astroY":398,
                "astroZ":504,
                "fuel":313
            },
            {
                "name":"РКЗП-321с",
                "type":"gasstation",
                "astroX":889,
                "astroY":543,
                "astroZ":695,
                "fuel":334
            }
        ]
    },
    {
        "name":"РКЗП-4568",
        "type":"gasstation",
        "astroX":949,
        "astroY":83,
        "astroZ":592,
        "directions":[
            {
                "name":"Сакулак",
                "type":"planet",
                "astroX":933,
                "astroY":301,
                "astroZ":620,
                "fuel":347
            },
            {
                "name":"Вишну",
                "type":"planet",
                "astroX":711,
                "astroY":163,
                "astroZ":620,
                "fuel":2006
            }
        ]
    },
    {
        "name":"Вишну",
        "type":"planet",
        "astroX":711,
        "astroY":163,
        "astroZ":620,
        "directions":[
            {
                "name":"РКЗП-4568",
                "type":"gasstation",
                "astroX":949,
                "astroY":83,
                "astroZ":592,
                "fuel":2006
            },
            {
                "name":"Сакулак",
                "type":"planet",
                "astroX":933,
                "astroY":301,
                "astroZ":620,
                "fuel":5781
            }
        ]
    },
    {
        "name":"Флостон",
        "type":"planet",
        "astroX":999,
        "astroY":475,
        "astroZ":620,
        "directions":[
            {
                "name":"Сакулак",
                "type":"planet",
                "astroX":933,
                "astroY":301,
                "astroZ":620,
                "fuel":3854
            }
        ]
    },
    {
        "name":"РКЗП-1649",
        "type":"gasstation",
        "astroX":709,
        "astroY":398,
        "astroZ":504,
        "directions":[
            {
                "name":"Сакулак",
                "type":"planet",
                "astroX":933,
                "astroY":301,
                "astroZ":620,
                "fuel":313
            },
            {
                "name":"Брауни",
                "type":"planet",
                "astroX":492,
                "astroY":450,
                "astroZ":620,
                "fuel":4984
            },
            {
                "name":"Вен-Тонг",
                "type":"planet",
                "astroX":614,
                "astroY":670,
                "astroZ":621,
                "fuel":338
            }
        ]
    },
    {
        "name":"РКЗП-321с",
        "type":"gasstation",
        "astroX":889,
        "astroY":543,
        "astroZ":695,
        "directions":[
            {
                "name":"Сакулак",
                "type":"planet",
                "astroX":933,
                "astroY":301,
                "astroZ":620,
                "fuel":334
            },
            {
                "name":"Фитрит",
                "type":"planet",
                "astroX":802,
                "astroY":822,
                "astroZ":621,
                "fuel":5040
            },
            {
                "name":"Вен-Тонг",
                "type":"planet",
                "astroX":614,
                "astroY":670,
                "astroZ":621,
                "fuel":326
            }
        ]
    },
    {
        "name":"Брауни",
        "type":"planet",
        "astroX":492,
        "astroY":450,
        "astroZ":620,
        "directions":[
            {
                "name":"РКЗП-1649",
                "type":"gasstation",
                "astroX":709,
                "astroY":398,
                "astroZ":504,
                "fuel":4984
            }
        ]
    },
    {
        "name":"Вен-Тонг",
        "type":"planet",
        "astroX":614,
        "astroY":670,
        "astroZ":621,
        "directions":[
            {
                "name":"РКЗП-1649",
                "type":"gasstation",
                "astroX":709,
                "astroY":398,
                "astroZ":504,
                "fuel":338
            },
            {
                "name":"РКЗП-321с",
                "type":"gasstation",
                "astroX":889,
                "astroY":543,
                "astroZ":695,
                "fuel":326
            },
            {
                "name":"Фитрит",
                "type":"planet",
                "astroX":802,
                "astroY":822,
                "astroZ":621,
                "fuel":2037
            },
            {
                "name":"РКЗП-3А67",
                "type":"gasstation",
                "astroX":518,
                "astroY":853,
                "astroZ":542,
                "fuel":313
            },
            {
                "name":"Траяна",
                "type":"planet",
                "astroX":499,
                "astroY":668,
                "astroZ":572,
                "fuel":3568
            }
        ]
    },
    {
        "name":"Траяна",
        "type":"planet",
        "astroX":499,
        "astroY":668,
        "astroZ":572,
        "directions":[
            {
                "name":"Вен-Тонг",
                "type":"planet",
                "astroX":614,
                "astroY":670,
                "astroZ":621,
                "fuel":3568
            }
        ]
    },
    {
        "name":"Фитрит",
        "type":"planet",
        "astroX":802,
        "astroY":822,
        "astroZ":621,
        "directions":[
            {
                "name":"РКЗП-321с",
                "type":"gasstation",
                "astroX":889,
                "astroY":543,
                "astroZ":695,
                "fuel":5040
            },
            {
                "name":"Вен-Тонг",
                "type":"planet",
                "astroX":614,
                "astroY":670,
                "astroZ":621,
                "fuel":2037
            },
            {
                "name":"Канк",
                "type":"planet",
                "astroX":658,
                "astroY":1103,
                "astroZ":620,
                "fuel":5565
            }
        ]
    },
    {
        "name":"РКЗП-3А67",
        "type":"gasstation",
        "astroX":518,
        "astroY":853,
        "astroZ":542,
        "directions":[
            {
                "name":"Вен-Тонг",
                "type":"planet",
                "astroX":614,
                "astroY":670,
                "astroZ":621,
                "fuel":313
            },
            {
                "name":"Канк",
                "type":"planet",
                "astroX":658,
                "astroY":1103,
                "astroZ":620,
                "fuel":5623
            },
            {
                "name":"РКЗП-5672",
                "type":"gasstation",
                "astroX":361,
                "astroY":1005,
                "astroZ":613,
                "fuel":114
            }
        ]
    },
    {
        "name":"Канк",
        "type":"planet",
        "astroX":658,
        "astroY":1103,
        "astroZ":620,
        "directions":[
            {
                "name":"Фитрит",
                "type":"planet",
                "astroX":802,
                "astroY":822,
                "astroZ":621,
                "fuel":5565
            },
            {
                "name":"РКЗП-3А67",
                "type":"gasstation",
                "astroX":518,
                "astroY":853,
                "astroZ":542,
                "fuel":5623
            },
            {
                "name":"Жемчужина",
                "type":"planet",
                "astroX":606,
                "astroY":1282,
                "astroZ":572,
                "fuel":4021
            }
        ]
    },
    {
        "name":"РКЗП-5672",
        "type":"gasstation",
        "astroX":361,
        "astroY":1005,
        "astroZ":613,
        "directions":[
            {
                "name":"РКЗП-3А67",
                "type":"gasstation",
                "astroX":518,
                "astroY":853,
                "astroZ":542,
                "fuel":114
            },
            {
                "name":"Гуан-Ди",
                "type":"planet",
                "astroX":232,
                "astroY":989,
                "astroZ":621,
                "fuel":6387
            },
            {
                "name":"Облако Цунь",
                "type":"astercloud",
                "astroX":309,
                "astroY":1152,
                "astroZ":684,
                "fuel":317
            },
            {
                "name":"А2М18",
                "type":"asteroid",
                "astroX":313,
                "astroY":1441,
                "astroZ":497,
                "fuel":341
            },
            {
                "name":"Мелиноя",
                "type":"planet",
                "astroX":453,
                "astroY":1382,
                "astroZ":571,
                "fuel":350
            }
        ]
    },
    {
        "name":"Гуан-Ди",
        "type":"planet",
        "astroX":232,
        "astroY":989,
        "astroZ":621,
        "directions":[
            {
                "name":"РКЗП-5672",
                "type":"gasstation",
                "astroX":361,
                "astroY":1005,
                "astroZ":613,
                "fuel":6387
            }
        ]
    },
    {
        "name":"Облако Цунь",
        "type":"astercloud",
        "astroX":309,
        "astroY":1152,
        "astroZ":684,
        "directions":[
            {
                "name":"РКЗП-5672",
                "type":"gasstation",
                "astroX":361,
                "astroY":1005,
                "astroZ":613,
                "fuel":317
            },
            {
                "name":"РКЗП-4531",
                "type":"gasstation",
                "astroX":454,
                "astroY":1200,
                "astroZ":504,
                "fuel":310
            },
            {
                "name":"Мелиноя",
                "type":"planet",
                "astroX":453,
                "astroY":1382,
                "astroZ":571,
                "fuel":311
            },
            {
                "name":"А2М18",
                "type":"asteroid",
                "astroX":313,
                "astroY":1441,
                "astroZ":497,
                "fuel":317
            },
            {
                "name":"Приисковый",
                "type":"asteroid",
                "astroX":219,
                "astroY":1273,
                "astroZ":552,
                "fuel":329
            }
        ]
    },
    {
        "name":"РКЗП-4531",
        "type":"gasstation",
        "astroX":454,
        "astroY":1200,
        "astroZ":504,
        "directions":[
            {
                "name":"Облако Цунь",
                "type":"astercloud",
                "astroX":309,
                "astroY":1152,
                "astroZ":684,
                "fuel":310
            },
            {
                "name":"Мелиноя",
                "type":"planet",
                "astroX":453,
                "astroY":1382,
                "astroZ":571,
                "fuel":349
            },
            {
                "name":"Жемчужина",
                "type":"planet",
                "astroX":606,
                "astroY":1282,
                "astroZ":572,
                "fuel":1628
            }
        ]
    },
    {
        "name":"Жемчужина",
        "type":"planet",
        "astroX":606,
        "astroY":1282,
        "astroZ":572,
        "directions":[
            {
                "name":"Канк",
                "type":"planet",
                "astroX":658,
                "astroY":1103,
                "astroZ":620,
                "fuel":4021
            },
            {
                "name":"РКЗП-4531",
                "type":"gasstation",
                "astroX":454,
                "astroY":1200,
                "astroZ":504,
                "fuel":1628
            },
            {
                "name":"Мелиноя",
                "type":"planet",
                "astroX":453,
                "astroY":1382,
                "astroZ":571,
                "fuel":5460
            },
            {
                "name":"РКЗП-G14F8",
                "type":"gasstation",
                "astroX":563,
                "astroY":1486,
                "astroZ":682,
                "fuel":2063
            }
        ]
    },
    {
        "name":"Приисковый",
        "type":"asteroid",
        "astroX":219,
        "astroY":1273,
        "astroZ":552,
        "directions":[
            {
                "name":"Облако Цунь",
                "type":"astercloud",
                "astroX":309,
                "astroY":1152,
                "astroZ":684,
                "fuel":329
            },
            {
                "name":"А2М18",
                "type":"asteroid",
                "astroX":313,
                "astroY":1441,
                "astroZ":497,
                "fuel":323
            },
            {
                "name":"Бей-Доу",
                "type":"planet",
                "astroX":125,
                "astroY":1562,
                "astroZ":572,
                "fuel":3821
            }
        ]
    },
    {
        "name":"Бей-Доу",
        "type":"planet",
        "astroX":125,
        "astroY":1562,
        "astroZ":572,
        "directions":[
            {
                "name":"Приисковый",
                "type":"asteroid",
                "astroX":219,
                "astroY":1273,
                "astroZ":552,
                "fuel":3821
            }
        ]
    },
    {
        "name":"Мелиноя",
        "type":"planet",
        "astroX":453,
        "astroY":1382,
        "astroZ":571,
        "directions":[
            {
                "name":"Облако Цунь",
                "type":"astercloud",
                "astroX":309,
                "astroY":1152,
                "astroZ":684,
                "fuel":311
            },
            {
                "name":"РКЗП-5672",
                "type":"gasstation",
                "astroX":361,
                "astroY":1005,
                "astroZ":613,
                "fuel":350
            },
            {
                "name":"РКЗП-4531",
                "type":"gasstation",
                "astroX":454,
                "astroY":1200,
                "astroZ":504,
                "fuel":349
            },
            {
                "name":"Жемчужина",
                "type":"planet",
                "astroX":606,
                "astroY":1282,
                "astroZ":572,
                "fuel":5460
            },
            {
                "name":"РКЗП-6493",
                "type":"gasstation",
                "astroX":432,
                "astroY":1644,
                "astroZ":675,
                "fuel":309
            }
        ]
    },
    {
        "name":"А2М18",
        "type":"asteroid",
        "astroX":313,
        "astroY":1441,
        "astroZ":497,
        "directions":[
            {
                "name":"Приисковый",
                "type":"asteroid",
                "astroX":219,
                "astroY":1273,
                "astroZ":552,
                "fuel":323
            },
            {
                "name":"Облако Цунь",
                "type":"astercloud",
                "astroX":309,
                "astroY":1152,
                "astroZ":684,
                "fuel":317
            },
            {
                "name":"РКЗП-5672",
                "type":"gasstation",
                "astroX":361,
                "astroY":1005,
                "astroZ":613,
                "fuel":341
            },
            {
                "name":"РКЗП-6493",
                "type":"gasstation",
                "astroX":432,
                "astroY":1644,
                "astroZ":675,
                "fuel":317
            }
        ]
    },
    {
        "name":"РКЗП-G14F8",
        "type":"gasstation",
        "astroX":563,
        "astroY":1486,
        "astroZ":682,
        "directions":[
            {
                "name":"Жемчужина",
                "type":"planet",
                "astroX":606,
                "astroY":1282,
                "astroZ":572,
                "fuel":2063
            },
            {
                "name":"РКЗП-6493",
                "type":"gasstation",
                "astroX":432,
                "astroY":1644,
                "astroZ":675,
                "fuel":329
            },
            {
                "name":"Венеция",
                "type":"planet",
                "astroX":598,
                "astroY":1659,
                "astroZ":502,
                "fuel":320
            }
        ]
    },
    {
        "name":"РКЗП-6493",
        "type":"gasstation",
        "astroX":432,
        "astroY":1644,
        "astroZ":675,
        "directions":[
            {
                "name":"А2М18",
                "type":"asteroid",
                "astroX":313,
                "astroY":1441,
                "astroZ":497,
                "fuel":317
            },
            {
                "name":"Мелиноя",
                "type":"planet",
                "astroX":453,
                "astroY":1382,
                "astroZ":571,
                "fuel":309
            },
            {
                "name":"РКЗП-G14F8",
                "type":"gasstation",
                "astroX":563,
                "astroY":1486,
                "astroZ":682,
                "fuel":329
            },
            {
                "name":"Венеция",
                "type":"planet",
                "astroX":598,
                "astroY":1659,
                "astroZ":502,
                "fuel":305
            },
            {
                "name":"Колумбарий",
                "type":"planet",
                "astroX":484,
                "astroY":1825,
                "astroZ":664,
                "fuel":311
            }
        ]
    },
    {
        "name":"Венеция",
        "type":"planet",
        "astroX":598,
        "astroY":1659,
        "astroZ":502,
        "directions":[
            {
                "name":"РКЗП-G14F8",
                "type":"gasstation",
                "astroX":563,
                "astroY":1486,
                "astroZ":682,
                "fuel":320
            },
            {
                "name":"РКЗП-6493",
                "type":"gasstation",
                "astroX":432,
                "astroY":1644,
                "astroZ":675,
                "fuel":305
            },
            {
                "name":"РКЗП-1234",
                "type":"gasstation",
                "astroX":724,
                "astroY":1664,
                "astroZ":587,
                "fuel":334
            },
            {
                "name":"Валькирия",
                "type":"planet",
                "astroX":828,
                "astroY":1811,
                "astroZ":618,
                "fuel":308
            },
            {
                "name":"Ника",
                "type":"planet",
                "astroX":753,
                "astroY":1946,
                "astroZ":507,
                "fuel":301
            }
        ]
    },
    {
        "name":"Колумбарий",
        "type":"planet",
        "astroX":484,
        "astroY":1825,
        "astroZ":664,
        "directions":[
            {
                "name":"РКЗП-6493",
                "type":"gasstation",
                "astroX":432,
                "astroY":1644,
                "astroZ":675,
                "fuel":311
            },
            {
                "name":"Валькирия",
                "type":"planet",
                "astroX":828,
                "astroY":1811,
                "astroZ":618,
                "fuel":315
            },
            {
                "name":"Ника",
                "type":"planet",
                "astroX":753,
                "astroY":1946,
                "astroZ":507,
                "fuel":343
            },
            {
                "name":"РКЗП-1220",
                "type":"gasstation",
                "astroX":522,
                "astroY":1979,
                "astroZ":633,
                "fuel":323
            }
        ]
    },
    {
        "name":"РКЗП-1220",
        "type":"gasstation",
        "astroX":522,
        "astroY":1979,
        "astroZ":633,
        "directions":[
            {
                "name":"Колумбарий",
                "type":"planet",
                "astroX":484,
                "astroY":1825,
                "astroZ":664,
                "fuel":323
            },
            {
                "name":"Лето",
                "type":"planet",
                "astroX":118,
                "astroY":1957,
                "astroZ":620,
                "fuel":3198
            }
        ]
    },
    {
        "name":"Лето",
        "type":"planet",
        "astroX":118,
        "astroY":1957,
        "astroZ":620,
        "directions":[
            {
                "name":"РКЗП-1220",
                "type":"gasstation",
                "astroX":522,
                "astroY":1979,
                "astroZ":633,
                "fuel":3198
            }
        ]
    },
    {
        "name":"РКЗП-1234",
        "type":"gasstation",
        "astroX":724,
        "astroY":1664,
        "astroZ":587,
        "directions":[
            {
                "name":"Раная",
                "type":"planet",
                "astroX":884,
                "astroY":1482,
                "astroZ":621,
                "fuel":1573
            },
            {
                "name":"Валькирия",
                "type":"planet",
                "astroX":828,
                "astroY":1811,
                "astroZ":618,
                "fuel":306
            },
            {
                "name":"Венеция",
                "type":"planet",
                "astroX":598,
                "astroY":1659,
                "astroZ":502,
                "fuel":334
            }
        ]
    },
    {
        "name":"Раная",
        "type":"planet",
        "astroX":884,
        "astroY":1482,
        "astroZ":621,
        "directions":[
            {
                "name":"РКЗП-1234",
                "type":"gasstation",
                "astroX":724,
                "astroY":1664,
                "astroZ":587,
                "fuel":1573
            }
        ]
    },
    {
        "name":"Валькирия",
        "type":"planet",
        "astroX":828,
        "astroY":1811,
        "astroZ":618,
        "directions":[
            {
                "name":"РКЗП-1234",
                "type":"gasstation",
                "astroX":724,
                "astroY":1664,
                "astroZ":587,
                "fuel":306
            },
            {
                "name":"Венеция",
                "type":"planet",
                "astroX":598,
                "astroY":1659,
                "astroZ":502,
                "fuel":308
            },
            {
                "name":"Колумбарий",
                "type":"planet",
                "astroX":484,
                "astroY":1825,
                "astroZ":664,
                "fuel":315
            },
            {
                "name":"Лебедь",
                "type":"planet",
                "astroX":976,
                "astroY":1786,
                "astroZ":572,
                "fuel":3788
            }
        ]
    },
    {
        "name":"Ника",
        "type":"planet",
        "astroX":753,
        "astroY":1946,
        "astroZ":507,
        "directions":[
            {
                "name":"Венеция",
                "type":"planet",
                "astroX":598,
                "astroY":1659,
                "astroZ":502,
                "fuel":301
            },
            {
                "name":"Колумбарий",
                "type":"planet",
                "astroX":484,
                "astroY":1825,
                "astroZ":664,
                "fuel":343
            }
        ]
    },
    {
        "name":"Лебедь",
        "type":"planet",
        "astroX":976,
        "astroY":1786,
        "astroZ":572,
        "directions":[
            {
                "name":"Валькирия",
                "type":"planet",
                "astroX":828,
                "astroY":1811,
                "astroZ":618,
                "fuel":3788
            },
            {
                "name":"РКЗП(А)-2981",
                "type":"gasstation",
                "astroX":916,
                "astroY":1966,
                "astroZ":567,
                "fuel":6267
            }
        ]
    },
    {
        "name":"РКЗП(А)-2981",
        "type":"gasstation",
        "astroX":916,
        "astroY":1966,
        "astroZ":567,
        "directions":[
            {
                "name":"Лебедь",
                "type":"planet",
                "astroX":976,
                "astroY":1786,
                "astroZ":572,
                "fuel":6267
            }
        ]
    },
    {
        "name":"Скопление Джонсон",
        "type":"astercloud",
        "astroX":1230,
        "astroY":1747,
        "astroZ":3248
    },
    {
        "name":"ЛСВ-37",
        "type":"-",
        "astroX":846,
        "astroY":183,
        "astroZ":702
    },
    {
        "name":"ЛСВ-43",
        "type":"-",
        "astroX":369,
        "astroY":1879,
        "astroZ":702
    },
    {
        "name":"ЛСВ-26",
        "type":"-",
        "astroX":649,
        "astroY":819,
        "astroZ":702
    }
]

module.exports = astroObjects;